students = [
    'mbullivent0@accuweather.com',
    'mphilliphs1@pagesperso-orange.fr',
    'varmour2@amazon.co.jp',
    'mhollier3@usgs.gov',
    'krosone4@msu.edu',
    'jcomsty5@dmoz.org',
    'maldie6@constantcontact.com',
    'thadkins7@goodreads.com',
    'bpittel8@ameblo.jp',
    'bdundon9@cmu.edu',
    'jbolmanna@walmart.com',
    'akinneyb@senate.gov',
    'aounsworthc@icq.com',
    'ckeverend@illinois.edu',
    'possipenkoe@addthis.com',
    'mmeritf@sun.com',
    'hgemnettg@linkedin.com',
    'ccreboeh@dailymotion.com',
    'bruleri@google.fr',
    'krickarseyj@accuweather.com',
    'fdowdellk@mit.edu',
    'cfrazerl@w3.org',
    'dshattockm@google.com',
    'gandraschn@unblog.fr',
    'hvanhestereno@rakuten.co.jp',
    'ulupartip@indiatimes.com',
    'eyewmanq@yahoo.co.jp',
    'kpotapczukr@vinaora.com',
    'lbramleys@blogger.com',
    'arowlsont@printfriendly.com',
    'slevesleyu@reuters.com',
    'rtembyv@xrea.com',
    'cgrumblew@surveymonkey.com',
    'dstowellx@dailymotion.com',
    'dbaalhamy@opensource.org',
    'cbackhousez@ca.gov',
    'bfrancesco10@cnbc.com',
    'jblades11@wordpress.org',
    'bbrunker12@biblegateway.com',
    'twitten13@springer.com',
    'dmarrian14@wp.com',
    'kjelfs15@google.co.jp',
    'rvanderbrug16@networksolutions.com',
    'dchitson17@ehow.com',
    'mjane18@sitemeter.com',
    'btinline19@shutterfly.com',
    'dknudsen1a@deliciousdays.com',
    'kmccraine1b@slate.com',
    'jmilksop1c@blogs.com',
    'scherry1d@oracle.com',
    'gjapp1e@imdb.com',
    'itoward1f@gravatar.com',
    'fbrosetti1g@bbb.org',
    'ryeldham1h@livejournal.com',
    'jkilrow1i@t.co',
    'ahammerberg1j@sbwire.com',
    'rschechter1k@senate.gov',
    'lbeevers1l@cbslocal.com',
    'gadamowicz1m@artisteer.com',
    'kothen1n@slashdot.org',
    'tbrobyn1o@cam.ac.uk',
    'ialcock1p@pbs.org',
    'krodenborch1q@chronoengine.com',
    'mhinkensen1r@accuweather.com',
    'cprop1s@hao123.com',
    'pmorde1t@tripod.com',
    'dheasly1u@nature.com',
    'rjiras1v@bluehost.com',
    'jwidger1w@sohu.com',
    'dbentame1x@pen.io',
    'adring1y@symantec.com',
    'htchir1z@ning.com',
    'icomiam20@ihg.com',
    'kbendare21@washington.edu',
    'bbaselio22@slate.com',
    'dcowthart23@ihg.com',
    'hwilfling24@mlb.com',
    'ebatkin25@latimes.com',
    'pcherrie26@goo.gl',
    'vjambrozek27@hud.gov',
    'bcamamill28@kickstarter.com',
    'fglayzer29@sun.com',
    'kchilles2a@census.gov',
    'rhiseman2b@scientificamerican.com',
    'fdowne2c@pen.io',
    'pdignam2d@engadget.com',
    'etift2e@blogspot.com',
    'mloxly2f@joomla.org',
    'ajoderli2g@umich.edu',
    'jnutley2h@smugmug.com',
    'lpudner2i@google.fr',
    'amapis2j@51.la',
    'jparnham2k@yolasite.com',
    'nalvarado2l@msu.edu',
    'dmoretto2m@yellowpages.com',
    'ljanak2n@toplist.cz',
    'agantzer2o@vkontakte.ru',
    'arichings2p@apple.com',
    'smelloi2q@pcworld.com'
]

registered_students = {
    'mbullivent0@accuweather.com': 'present',
    'mphilliphs1@pagesperso-orange.fr': 'present',
    'varmour2@amazon.co.jp': 'absent',
    'mhollier3@usgs.gov': 'absent',
    'krosone4@msu.edu': 'absent',
    'jcomsty5@dmoz.org': 'absent',
    'maldie6@constantcontact.com': 'present',
    'thadkins7@goodreads.com': 'absent',
    'bpittel8@ameblo.jp': 'present',
    'bdundon9@cmu.edu': 'absent',
    'jbolmanna@walmart.com': 'present',
    'akinneyb@senate.gov': 'absent',
    'aounsworthc@icq.com': 'present',
    'ckeverend@illinois.edu': 'present',
    'possipenkoe@addthis.com': 'present',
    'mmeritf@sun.com': 'absent',
    'hgemnettg@linkedin.com': 'present',
    'ccreboeh@dailymotion.com': 'absent',
    'bruleri@google.fr': 'absent',
    'krickarseyj@accuweather.com': 'absent',
    'fdowdellk@mit.edu': 'absent',
    'cfrazerl@w3.org': 'absent',
    'dshattockm@google.com': 'absent',
    'gandraschn@unblog.fr': 'absent',
    'hvanhestereno@rakuten.co.jp': 'absent',
    'ulupartip@indiatimes.com': 'present',
    'eyewmanq@yahoo.co.jp': 'absent',
    'kpotapczukr@vinaora.com': 'present',
    'lbramleys@blogger.com': 'absent',
    'arowlsont@printfriendly.com': 'absent',
    'slevesleyu@reuters.com': 'absent',
    'rtembyv@xrea.com': 'present',
    'cgrumblew@surveymonkey.com': 'present',
    'dstowellx@dailymotion.com': 'absent',
    'dbaalhamy@opensource.org': 'present',
    'cbackhousez@ca.gov': 'present',
    'bfrancesco10@cnbc.com': 'present',
    'jblades11@wordpress.org': 'present',
    'bbrunker12@biblegateway.com': 'present',
    'twitten13@springer.com': 'present',
    'dmarrian14@wp.com': 'absent',
    'kjelfs15@google.co.jp': 'present',
    'rvanderbrug16@networksolutions.com': 'absent',
    'dchitson17@ehow.com': 'absent',
    'mjane18@sitemeter.com': 'present',
    'btinline19@shutterfly.com': 'absent',
    'dknudsen1a@deliciousdays.com': 'present',
    'kmccraine1b@slate.com': 'absent',
    'jmilksop1c@blogs.com': 'absent',
    'scherry1d@oracle.com': 'absent',
    'gjapp1e@imdb.com': 'present',
    'itoward1f@gravatar.com': 'absent',
    'fbrosetti1g@bbb.org': 'absent',
    'ryeldham1h@livejournal.com': 'present',
    'jkilrow1i@t.co': 'absent',
    'ahammerberg1j@sbwire.com': 'present',
    'rschechter1k@senate.gov': 'absent',
    'lbeevers1l@cbslocal.com': 'absent',
    'gadamowicz1m@artisteer.com': 'present',
    'kothen1n@slashdot.org': 'present',
    'tbrobyn1o@cam.ac.uk': 'present',
    'ialcock1p@pbs.org': 'present',
    'krodenborch1q@chronoengine.com': 'absent',
    'mhinkensen1r@accuweather.com': 'present',
    'cprop1s@hao123.com': 'absent',
    'pmorde1t@tripod.com': 'present',
    'dheasly1u@nature.com': 'absent',
    'rjiras1v@bluehost.com': 'absent',
    'jwidger1w@sohu.com': 'absent',
    'dbentame1x@pen.io': 'present',
    'adring1y@symantec.com': 'absent',
    'htchir1z@ning.com': 'present',
    'icomiam20@ihg.com': 'present',
    'kbendare21@washington.edu': 'present',
    'bbaselio22@slate.com': 'present',
    'dcowthart23@ihg.com': 'absent',
    'hwilfling24@mlb.com': 'present',
    'ebatkin25@latimes.com': 'present',
    'pcherrie26@goo.gl': 'present',
    'vjambrozek27@hud.gov': 'absent',
    'bcamamill28@kickstarter.com': 'absent',
    'fglayzer29@sun.com': 'absent',
    'kchilles2a@census.gov': 'absent',
    'rhiseman2b@scientificamerican.com': 'absent',
    'fdowne2c@pen.io': 'present',
    'pdignam2d@engadget.com': 'present',
    'etift2e@blogspot.com': 'present',
    'mloxly2f@joomla.org': 'present',
    'ajoderli2g@umich.edu': 'present',
    'jnutley2h@smugmug.com': 'absent',
    'lpudner2i@google.fr': 'present',
    'amapis2j@51.la': 'absent',
    'jparnham2k@yolasite.com': 'present',
    'nalvarado2l@msu.edu': 'absent',
    'dmoretto2m@yellowpages.com': 'present',
    'ljanak2n@toplist.cz': 'absent',
    'agantzer2o@vkontakte.ru': 'present',
    'arichings2p@apple.com': 'absent',
    'smelloi2q@pcworld.com': 'absent'
}

events = [
    'event-312980','event-367821','event-924358','event-925146','event-871053',
    'event-018597','event-249016','event-987015','event-692358','event-160935',
    'event-604938','event-852746','event-679230','event-250378','event-261573',
    'event-290837','event-613089','event-123549','event-724568','event-629507',
    'event-298315','event-349678','event-359472','event-573824','event-158340',
    'event-714389','event-456091','event-547362','event-259847','event-798046',
    'event-387950','event-738602','event-025947','event-046197','event-945360',
    'event-760142','event-952738','event-513980','event-247156','event-912857',
    'event-032965','event-793460','event-153487','event-248071','event-185670',
    'event-963410','event-085964','event-093258','event-634981','event-306954',
    'event-397152','event-478659','event-093681','event-697341','event-214509',
    'event-896304','event-459768','event-650821','event-841265','event-129386',
    'event-063197','event-429386','event-625473','event-916837','event-320975',
    'event-291465','event-496072','event-903764','event-365197','event-658390',
    'event-584169','event-397041','event-524968','event-163985','event-725608',
    'event-801396','event-397501','event-120463','event-723415','event-078146',
    'event-852467','event-475690','event-927316','event-794132','event-561409',
    'event-064237','event-793216','event-789104','event-378061','event-294530',
    'event-269407','event-061749','event-305947','event-431960','event-654381',
    'event-673918','event-521047','event-536018','event-451962','event-108462'
]

event = 'event-473111'
